services:
  backend:
    build:
      context: .
      dockerfile: src/backend/backend.Dockerfile
    ports:
      - "8000:8000" # outside_port : inside_port
    env_file: .env
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: src/frontend/frontend.Dockerfile
    ports:
      - "8501:8501"
    environment:
      # Use the service name defined above as the hostname
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
